### ISSUE TITLE
Resolve issues from upstream repository

### ISSUE THREAD

**Issue by crissdev** [crissdev/knockout.mapping#5]
Try to merge valid PRs from upstream repository and fix issues.
- [x] Fix SteveSanderson#124 - Use hasOwnProperty to check for bucket existence 1cf041d950529662eca35e50b7acb075c791e14c (PR SteveSanderson#173)
- [x] Put null check first in canHaveProperties 57a0b56c6368bb3b8816fb0d78c35820aa719bf3 (PR SteveSanderson#149)
- [x] Use intermediate vars to decrease minified size f97d5cde145962af919a6472d22418f9f0f43626 (PR  SteveSanderson#151)
- [x] Only get types once in mergeArrays e6c56313d22375e0e1ac7242f18dce9811577ad2 (PR SteveSanderson#148)
- [x] Incorrect handling of properties with periods (SteveSanderson#96)
- [x] allow `JSON.stringify` parameters to be specified to `ko.mapping.toJSON` 8e55292c826ceadcd5bc52986433d09c8aad73fd (SteveSanderson#205)
- [ ] `include` option is not working properly (SteveSanderson#176) - **to verify**
- [x] Mapping doesn't work when properties listed in different order (SteveSanderson#203)

**Comment by crissdev** [comment]
@tjyrkinen If time permits please take a look at SteveSanderson#176 (see above). It will help a lot in moving forward and getting close to v3.0. Thanks.
